config/routes.rb
Railsblog::Application.routes.draw do
  
  resources :posts do
    resources :comments
  end

  root 'welcome#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  # Posts have comments, and tell Rails to automagically delete all comments for a post when it is deleted
  has_many :comments, dependent: :destroy

  # Only let Posts be created that a) have a title, and b) the title has to have at least 5 characters
  validates :title, presence: true,
                    length: { minimum: 5 }


  # def popular?
  #   # if self.comments.count >= 5
  #   #   return true
  #   # else
  #   #   return false
  #   # end

  #   # This line is the same as the five lines above. It's called the "ternary operator". Google it.
  #   self.comments.count >= 5 ? true : false
  # end

  # def long_title?
  #   # http://ruby-doc.org/core-2.0.0/String.html#method-i-split
  #   title_as_word_array = self.title.split(" ")

  #   # Another instance of the ternary operator. It rocks.
  #   title_as_word_array.size > 5 ? true : false
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # See posts controller. This time, we only force the name/password when they try to delete a comment.
  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    # A Comment belongs to only one Post, so find the Post this Comment will be attached to
    @post = Post.find(params[:post_id])
    # Create a Comment that's linked to the Post and fill it with the commenter's name and his/her comment
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to post_path(@post)
  end

  def destroy
    # A Comment belongs to only one Post, so find the Post this Comment will be attached to
    @post = Post.find(params[:post_id])
    # Grab the comment we're trying to delete
    @comment = @post.comments.find(params[:id])
    # Delete the comment
    @comment.destroy
    # Send the user back to the Post you deleted the Comment from.
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # Force the user to type the correct username and password to do anything in the Posts controller except for viewing the index or a single post. Feel free to change the name/password to something else.
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    # Create a @posts instance variable and fill it with all the posts in the database
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    # Create a @post instance variable, fetch the Post from the database with the id in the params hash, and fill it with the Post pulled from the DB.
    @post = Post.find(params[:id])
  end

  def edit
    # Create a @post instance variable, fetch the Post from the database with the id in the params hash, and fill it with the Post pulled from the DB.
    @post = Post.find(params[:id])
  end

  def update
    # Create a @post instance variable, fetch the Post from the database with the id in the params hash, and fill it with the Post pulled from the DB.
    @post = Post.find(params[:id])
   
    if @post.update(post_params)
      # If @post updated correctly, redirect the user to it
      redirect_to @post
    else
      # Otherwise, send the user back to the form to try again
      render 'edit'
    end
  end

  def create
    # Create an instance variable that can be used in the view
    # Create a new instance of the Post model with the params (title & body) that came from the form
    @post = Post.new(post_params)

    # Try to actually save the post to the database instead of just holding it in memory
    if @post.save
      # If @post saved correctly, redirect the user to it
      redirect_to @post
    else
      # Otherwise, send the user back to the form to try again
      render 'new'
    end
  end

  def destroy
    # Create a @post instance variable, fetch the Post from the database with the id in the params hash, and fill it with the Post pulled from the DB.
    @post = Post.find(params[:id])
    # Nuke it!
    @post.destroy
    # Go back to the listing of all the posts
    redirect_to posts_path
  end


  # Methods below 'private' can only be acessed by methods inside this controller. There's no way to visit the route /posts/post_params. 
  private

    # Good ol' Rails 4 Strong Parameters...
    # http://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters
    def post_params
      # Remember how we created a new Post from the params? This line tells Rails to only allow the title and body to be set from the params. It's a major security improvement, but it seems wonky at first.
      params.require(:post).permit(:title, :text)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsblog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<p>
  <%= link_to 'New post', new_post_path %>
</p>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td><%= link_to 'Show', post %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post_path(post),
                method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>Write Something!</h1>

<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>
 
<h2>Comments</h2>
<%= render @post.comments %>
 
<h2>Add a comment:</h2>
<%= render "comments/form" %>
 
<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>

<!-- I don't like putting 'controller:' in my views unless I have to, but it works. -->
<%#= link_to "My Blog", controller: "posts" %>

<!-- This is how Rails prefers it: use the link helpers: -->
<%= link_to "My Blog", posts_path %>